require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'vendor/**/*'

# Disable overly strict or project-agnostic rules
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

# Rails-specific
Rails/I18nLocaleTexts:
  Enabled: false
